services:
  database:
    image: mariadb:latest
    restart: on-failure
    volumes:
      - database-volume:/var/lib/mysql
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pyplanet
      MYSQL_USER: pyplanet
      MYSQL_PASSWORD: pyplanet
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - server-network
  server:
    build:
      context: ../../build-server
      dockerfile: Dockerfile
    image: trackmania-server-docker:insalan-server
    restart: on-failure
    depends_on:
      - database
    environment:
      SERVER_TITLE: "Trackmania"
      SERVER_NAME: "Insalan Cup8"
    ports:
      - "2358:2358/tcp"
      - "2358:2358/udp"
#      - "3450:3450/tcp"
#      - "3450:3450/udp"
    expose:
      - 5005
    volumes:
      - ./cfg_server.xml:/home/server/tm_server/UserData/Config/cfg_server.xml:Z
      - ../maps:/home/server/tm_server/UserData/Maps:z
      - ./maps/MatchSettings:/home/server/tm_server/UserData/Maps/MatchSettings:z
    networks:
      - server-network
  controller:
    build:
      context: ../../build-pyplanet
      dockerfile: Dockerfile
    image: harha/trackmania-server-docker:insalan-pyplanet
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
      server:
        condition: service_started
    volumes:
      - ../pyplanet/settings:/home/server/pyplanet/settings:Z
      - ../maps:/home/server/tm_server/UserData/Maps:z
      - ./maps/MatchSettings:/home/server/tm_server/UserData/Maps/MatchSettings:z
    networks:
      - server-network

networks:
  server-network:
    driver: bridge

volumes:
  database-volume:
    driver: local
